# Generated by Django 3.0.8 on 2020-07-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered', models.DateField()),
                ('vaccination', models.BooleanField()),
                ('cage_num', models.CharField(max_length=16)),
            ],
        ),
    ]
